//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dataEntities : DbContext
    {
        public dataEntities()
            : base("name=dataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Candidate> tbl_Candidate { get; set; }
        public virtual DbSet<tbl_CandidateDocument> tbl_CandidateDocument { get; set; }
        public virtual DbSet<tbl_CandidateJobHistory> tbl_CandidateJobHistory { get; set; }
        public virtual DbSet<tbl_CandidateSkill> tbl_CandidateSkill { get; set; }
        public virtual DbSet<tbl_Country> tbl_Country { get; set; }
        public virtual DbSet<tbl_Document> tbl_Document { get; set; }
        public virtual DbSet<tbl_Skill> tbl_Skill { get; set; }
        public virtual DbSet<View_Candidate> View_Candidate { get; set; }
        public virtual DbSet<tbl_201_User> tbl_201_User { get; set; }
        public virtual DbSet<tbl_Stakeholder> tbl_Stakeholder { get; set; }
        public virtual DbSet<tbl_StakeholderType> tbl_StakeholderType { get; set; }
    
        public virtual ObjectResult<proc_ViewSaleTemp_Result> proc_ViewSaleTemp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ViewSaleTemp_Result>("proc_ViewSaleTemp");
        }
    
        public virtual ObjectResult<proc_View_Sale_Result> proc_View_Sale()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_View_Sale_Result>("proc_View_Sale");
        }
    
        public virtual ObjectResult<proc_ViewSaleV1_Result> proc_ViewSaleV1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ViewSaleV1_Result>("proc_ViewSaleV1");
        }
    
        public virtual ObjectResult<proc_ViewSaleV2_Result> proc_ViewSaleV2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ViewSaleV2_Result>("proc_ViewSaleV2");
        }
    
        public virtual ObjectResult<proc_ViewSaleV3_Result> proc_ViewSaleV3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ViewSaleV3_Result>("proc_ViewSaleV3");
        }
    
        public virtual ObjectResult<proc_ViewSaleV4_Result> proc_ViewSaleV4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ViewSaleV4_Result>("proc_ViewSaleV4");
        }
    
        public virtual ObjectResult<proc_ViewSaleV5_Result> proc_ViewSaleV5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ViewSaleV5_Result>("proc_ViewSaleV5");
        }
    
        public virtual ObjectResult<proc_ViewSaleV6_Result> proc_ViewSaleV6()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ViewSaleV6_Result>("proc_ViewSaleV6");
        }
    
        public virtual ObjectResult<proc_CustomDashboard_Result> proc_CustomDashboard(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_CustomDashboard_Result>("proc_CustomDashboard", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<proc_CustomDashboardV2_Result> proc_CustomDashboardV2(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_CustomDashboardV2_Result>("proc_CustomDashboardV2", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<proc_CustomDashboardV3_Result> proc_CustomDashboardV3(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_CustomDashboardV3_Result>("proc_CustomDashboardV3", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<proc_CustomDashboardV4_Result> proc_CustomDashboardV4(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_CustomDashboardV4_Result>("proc_CustomDashboardV4", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<proc_IESummery_Result> proc_IESummery(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_IESummery_Result>("proc_IESummery", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<proc_CustomDashboardV5_Result> proc_CustomDashboardV6(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_CustomDashboardV5_Result>("proc_CustomDashboardV6", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<proc_SOBreakdownByDateRange_Result> proc_SOBreakdownByDateRange(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_SOBreakdownByDateRange_Result>("proc_SOBreakdownByDateRange", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<proc_TransactionByDateRange_Result> proc_TransactionByDateRange(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_TransactionByDateRange_Result>("proc_TransactionByDateRange", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<proc_CustomDashboardV6_Result> proc_CustomDashboardV5(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_CustomDashboardV6_Result>("proc_CustomDashboardV5", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<proc_CustomDashboardV7_Result> proc_CustomDashboardV7(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_CustomDashboardV7_Result>("proc_CustomDashboardV7", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<proc_ViewConsumerOrderStatusPivotReport_Result> proc_ViewConsumerOrderStatusPivotReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ViewConsumerOrderStatusPivotReport_Result>("proc_ViewConsumerOrderStatusPivotReport");
        }
    
        public virtual ObjectResult<proc1_ViewConsumerOrderStatusPivotReport_Result> proc1_ViewConsumerOrderStatusPivotReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc1_ViewConsumerOrderStatusPivotReport_Result>("proc1_ViewConsumerOrderStatusPivotReport");
        }
    }
}
