//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StakeholderType
    {
        public int AutoId { get; set; }
        public int StakeHolderTypeId { get; set; }
        public string StakeHolderTypeName { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<int> ClientId { get; set; }
    }
}
