//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Stakeholder
    {
        public int AutoId { get; set; }
        public string StakeHolderUniqueCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Gender { get; set; }
        public string GuardianFullName { get; set; }
        public string GuardianContact { get; set; }
        public Nullable<int> RelationTypeId { get; set; }
        public Nullable<int> StakeHolderTypeId { get; set; }
        public string RefStakeHolderUniqueCode { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Remarks { get; set; }
        public string Address { get; set; }
    }
}
